# Generated by Django 5.1.6 on 2026-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
